{
  "name": "@casperengl/try-catch",
  "version": "1.6.1",
  "main": "lib/try-catch.js",
  "license": "MIT",
  "publishConfig": {
    "registry": "https://registry.npmjs.org/",
    "access": "public"
  },
  "devDependencies": {
    "@rollup/plugin-typescript": "^3.0.0",
    "@types/jest": "^24.0.23",
    "@typescript-eslint/eslint-plugin": "^2.7.0",
    "@typescript-eslint/parser": "^2.7.0",
    "axios": "^0.19.2",
    "eslint": "^6.6.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-plugin-import": "^2.18.2",
    "jest": "^24.9.0",
    "rollup": "^1.29.0",
    "rollup-plugin-terser": "^5.2.0",
    "ts-jest": "^24.1.0",
    "ts-loader": "^6.2.1",
    "typescript": "^3.7.4"
  },
  "peerDependencies": {
    "tslib": "^1.11.0"
  },
  "scripts": {
    "pretest": "npm run build",
    "test": "jest",
    "watch:test": "npm run test --watch",
    "build": "rollup -c rollup.config.js",
    "prepublishOnly": "npm test"
  },
  "description": "Package to trycatch code that accepts functions and promises",
  "directories": {
    "lib": "lib"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/CasperEngl/try-catch.git"
  },
  "author": "Casper Engelmann <me@casperengelmann.com>",
  "bugs": {
    "url": "https://github.com/CasperEngl/try-catch/issues"
  },
  "homepage": "https://github.com/CasperEngl/try-catch#readme"
}
